spring:
  application:
    name: contract-service
server:
  port: 8081
logging:
  level:
    root: WARN
    company.tothepoint: DEBUG
---

spring:
  profiles: docker
  data:
    mongodb:
      host: contract-mongo
  rabbitmq:
      host: rabbitmq
app:
  rabbitmq:
      host: rabbitmq