spring:
  application:
    name: contract-service
server:
  port: 8081
---

spring:
  profiles: docker
  data:
    mongodb:
      host: contract-mongo
  rabbitmq:
      host: rabbitmq
app:
  rabbitmq:
      host: rabbitmq